### PR TITLE
Supports building spel vagrant boxes from forks/pull requests

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Comment by lorengordon** [comment]
go vagrant go

**Comment by lorengordon** [comment]
go vagrant go

**Comment by lorengordon** [comment]
go vagrant go

**Comment by lorengordon** [comment]
go vagrant go

**Comment by lorengordon** [comment]
go vagrant go

**Comment by lorengordon** [comment]
@plus3it/spel this is ready for re-review...

**Comment by confusdcodr** [comment]
Looks like you need to rebase before merging this in

**Pull request merged**
