### PR TITLE
Adds spel and aws packages to el9 images

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Review by eemperor — DISMISSED** [review]

**Comment by lorengordon** [comment]
go codebuild go

**Comment by eemperor** [comment]
Approved pending CI

**Pull request merged**
