### PR TITLE
Installs amigen customization options into builder box

### PR DESCRIPTION
**Pull request by lorengordon**
* New PR Alert to: @plus3it/spel

### CODE REVIEW

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
@plus3it/spel looking good, this is ready for review.

**Comment by YakDriver** [comment]
Is there any advantage to being super robust about word splitting? Didn't think it was a big issue but just curious on your thoughts.

Instead of:
```bash
BUILDDEPS=(${SPEL_BUILDDEPS:-lvm2 parted yum-utils unzip git})
```
Some `read`:
```bash
IFS=" " read -r -a BUILDDEPS <<< "${SPEL_BUILDDEPS:-lvm2 parted yum-utils unzip git}"
```

**Comment by ferricoxide** [comment]
~~~~
 $ echo 'IFS=" " read -r -a BUILDDEPS <<< "${SPEL_BUILDDEPS:-lvm2 parted yum-utils unzip git}"' | wc -c
86
$ echo "BUILDDEPS=(${SPEL_BUILDDEPS:-lvm2 parted yum-utils unzip git})" | wc -c
44
~~~~

More gymnastics _and_ more key-strokes??

**Comment by YakDriver** [comment]
There's always
```console
$ echo 'set -f' | wc -c
7
```

**Pull request merged**
