### PR TITLE
Adds additional account IDs in AMI filter

### PR DESCRIPTION
**Pull request by eemperor**
Fixes # .

Changes offered/proposed in this pull request:
- 
- 
- 

* New PR Alert to: @plus3it/spel

### CODE REVIEW

**Comment by eemperor** [comment]
go p3 codebuild go

**Comment by eemperor** [comment]
go p3 codebuild go

**Comment by eemperor** [comment]
go codebuild go

**Comment by eemperor** [comment]
go p3 codebuild go

**Comment by eemperor** [comment]
go p3 codebuild go

**Comment by eemperor** [comment]
go p3 codebuild go

**Review by ferricoxide — APPROVED** [review]
Table's so wide it's difficult to review…

At any rate, once one can _see_ all the columns, everything looks right.

**Pull request merged**
