### PR TITLE
Releases spel 2024.06.1

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go vagrant go

**Review by ferricoxide — APPROVED** [review]
This the final month for new CentOS 8 Stream AMIs and EL AMIs?

**Comment by lorengordon** [comment]
> Sorry. My keyboard's `7` key is wonky. That should have been:
> 
> > …and EL **_7_** AMIs?

Well, I think we'll _try_ one more EL7 release for July, since RHEL7 EOM date is technically [June 30 2024](https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux/rhel-7-end-of-maintenance). Maybe there will be some updates in the repos that we'll pick up in one more build. But, if the repos aren't available, then yeah, this will be the last of the EL7 releases.

**Pull request merged**
