### PR TITLE
Pass var for fork/branch through

### PR DESCRIPTION
**Pull request by ferricoxide**
Need to be able to specify branch if we're allowing specification of fork

### CODE REVIEW

**Comment by ferricoxide** [comment]
go codebuild go

**Comment by ferricoxide** [comment]
go codebuild go

**Comment by ferricoxide** [comment]
go codebuild go

**Comment by ferricoxide** [comment]
go codebuild go

**Comment by ferricoxide** [comment]
go codebuild go

**Comment by ferricoxide** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Pull request merged**
