### PR TITLE
Supports installing additional rpms from non-default repos

### PR DESCRIPTION
**Pull request by lorengordon**
Previously, if AMIGENREPOS was specified, it was used exclusively. This allows AMIGENREPOS to be appended to the default repos. To disable the default repos, pass `spel_usedefaultrepos=false`.

This feature is used in this PR to install rpms from the spel-packages repo into the built images for both el7 and el8. The tests are also updated accordingly.

### CODE REVIEW

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
Demonstrating the manifest really is picking up the packages from the new repo, with *much* newer versions!

```diff
diff --git a/manifests/spel-minimal-centos-7-hvm.manifest.txt b/manifests/spel-minimal-centos-7-hvm.manifest.txt
index 4698303..a6747a1 100644
--- a/manifests/spel-minimal-centos-7-hvm.manifest.txt
+++ b/manifests/spel-minimal-centos-7-hvm.manifest.txt
@@ -1,6 +1,6 @@
 CentOS Linux release 7.9.2009 (Core)
-aws-cli/1.22.11 Python/3.6.8 Linux/3.10.0-1062.1.2.el7.x86_64 botocore/1.23.11
-aws-cli/2.4.0 Python/3.8.8 Linux/3.10.0-1062.1.2.el7.x86_64 exe/x86_64.centos.7 prompt/off
+aws-cli/1.22.24 Python/3.6.8 Linux/3.10.0-1160.el7.x86_64 botocore/1.23.24
+aws-cli/2.4.6 Python/3.8.8 Linux/3.10.0-1160.el7.x86_64 exe/x86_64.centos.7 prompt/off
 acl-2.2.51-15.el7.x86_64
 acpid-2.0.19-9.el7.x86_64
 alsa-lib-1.1.8-1.el7.x86_64
@@ -8,7 +8,7 @@ amazon-ecr-credential-helper-0.3.0-1.el7.x86_64
 amazon-efs-utils-1.10-1.el7.noarch
 amazon-linux-extras-1.6.9-2.el7.noarch
 amazon-linux-extras-yum-plugin-1.6.9-2.el7.noarch
-amazon-ssm-agent-2.3.1319.0-1.x86_64
+amazon-ssm-agent-3.1.715.0-1.x86_64
 atk-2.28.1-2.el7.x86_64
 audit-2.8.5-4.el7.x86_64
 audit-libs-2.8.5-4.el7.x86_64
@@ -28,9 +28,9 @@ aws-apitools-rds-1.19.002-1.0.el7.noarch
 aws-cfn-bootstrap-1.4-31.el7.noarch
 aws-scripts-ses-2014.05.14-1.2.el7.noarch
 basesystem-10.0-7.el7.centos.noarch
-bash-4.2.46-34.el7.x86_64
+bash-4.2.46-35.el7_9.x86_64
 bc-1.06.95-13.el7.x86_64
-bind-export-libs-9.11.4-26.P2.el7_9.7.x86_64
+bind-export-libs-9.11.4-26.P2.el7_9.8.x86_64
 binutils-2.27-44.base.el7_9.1.x86_64
 btrfs-progs-4.9.1-1.el7.x86_64
 bzip2-libs-1.0.6-13.el7.x86_64
@@ -78,9 +78,9 @@ dracut-network-033-572.el7.x86_64
 e2fsprogs-1.42.9-19.el7.x86_64
 e2fsprogs-libs-1.42.9-19.el7.x86_64
 ebtables-2.0.10-16.el7.x86_64
-ec2-hibinit-agent-1.0.0-4.el7.noarch
-ec2-instance-connect-1.1-11.el7.noarch
-ec2-net-utils-1.1-1.1.el7.noarch
+ec2-hibinit-agent-1.0.2-3.el7.noarch
+ec2-instance-connect-1.1-15.el7.noarch
+ec2-net-utils-1.5-3.el7.noarch
 ec2sys-autotune-1.0.7-1.el7.noarch
 ec2-utils-1.0-2.el7.noarch
 elfutils-default-yama-scope-0.176-5.el7.noarch
@@ -116,6 +116,7 @@ gnupg2-2.0.22-5.el7_5.x86_64
 gobject-introspection-1.56.1-1.el7.x86_64
 gpgme-1.3.2-5.el7.x86_64
 gpg-pubkey-352c64e5-52ae6884
+gpg-pubkey-e96e3db7-6196a254
 gpg-pubkey-f4a80eb5-53a7ff4b
 graphite2-1.3.10-1.el7_3.x86_64
 grep-2.20-3.el7.x86_64
@@ -155,19 +156,19 @@ java-1.8.0-openjdk-headless-1.8.0.312.b07-1.el7_9.x86_64
 javapackages-tools-3.4.1-11.el7.noarch
 jbigkit-libs-2.0-11.el7.x86_64
 json-c-0.11-4.el7_0.x86_64
-kbd-1.15.5-15.el7.x86_64
-kbd-legacy-1.15.5-15.el7.noarch
-kbd-misc-1.15.5-15.el7.noarch
-kernel-3.10.0-1160.45.1.el7.x86_64
-kernel-tools-3.10.0-1160.45.1.el7.x86_64
-kernel-tools-libs-3.10.0-1160.45.1.el7.x86_64
+kbd-1.15.5-16.el7_9.x86_64
+kbd-legacy-1.15.5-16.el7_9.noarch
+kbd-misc-1.15.5-16.el7_9.noarch
+kernel-3.10.0-1160.49.1.el7.x86_64
+kernel-tools-3.10.0-1160.49.1.el7.x86_64
+kernel-tools-libs-3.10.0-1160.49.1.el7.x86_64
 kexec-tools-2.0.15-51.el7_9.3.x86_64
 keyutils-1.5.8-3.el7.x86_64
 keyutils-libs-1.5.8-3.el7.x86_64
 kmod-20-28.el7.x86_64
 kmod-libs-20-28.el7.x86_64
 kpartx-0.4.9-135.el7_9.x86_64
-krb5-libs-1.15.1-50.el7.x86_64
+krb5-libs-1.15.1-51.el7_9.x86_64
 less-458-9.el7.x86_64
 libacl-2.2.51-15.el7.x86_64
 libaio-0.3.109-13.el7.x86_64
@@ -295,20 +296,20 @@ newt-0.52.15-4.el7.x86_64
 newt-python-0.52.15-4.el7.x86_64
 nfs-utils-1.3.0-0.68.el7.2.x86_64
 nspr-4.32.0-1.el7_9.x86_64
-nss-3.67.0-3.el7_9.x86_64
+nss-3.67.0-4.el7_9.x86_64
 nss-pem-1.0.3-7.el7.x86_64
 nss-softokn-3.67.0-3.el7_9.x86_64
 nss-softokn-freebl-3.67.0-3.el7_9.x86_64
-nss-sysinit-3.67.0-3.el7_9.x86_64
-nss-tools-3.67.0-3.el7_9.x86_64
+nss-sysinit-3.67.0-4.el7_9.x86_64
+nss-tools-3.67.0-4.el7_9.x86_64
 nss-util-3.67.0-1.el7_9.x86_64
 ntp-4.2.6p5-29.el7.centos.2.x86_64
 ntpdate-4.2.6p5-29.el7.centos.2.x86_64
 numactl-libs-2.0.12-5.el7.x86_64
 openldap-2.4.44-24.el7_9.x86_64
-openssh-7.4p1-21.el7.x86_64
-openssh-clients-7.4p1-21.el7.x86_64
-openssh-server-7.4p1-21.el7.x86_64
+openssh-7.4p1-22.el7_9.x86_64
+openssh-clients-7.4p1-22.el7_9.x86_64
+openssh-server-7.4p1-22.el7_9.x86_64
 openssl-1.0.2k-22.el7_9.x86_64
 openssl-libs-1.0.2k-22.el7_9.x86_64
 os-prober-1.58-9.el7.x86_64
@@ -429,7 +430,7 @@ python-libs-2.7.5-90.el7.x86_64
 python-linux-procfs-0.4.11-4.el7.noarch
 python-lxml-3.2.1-4.el7.x86_64
 python-markupsafe-0.11-10.el7.x86_64
-python-perf-3.10.0-1160.45.1.el7.x86_64
+python-perf-3.10.0-1160.49.1.el7.x86_64
 python-prettytable-0.7.2-3.el7.noarch
 python-pycurl-7.19.0-19.el7.x86_64
 python-pyudev-0.15-9.el7.noarch
@@ -450,10 +451,10 @@ rdma-core-22.4-6.el7_9.x86_64
 readline-6.2-11.el7.x86_64
 rootfiles-8.1-11.el7.noarch
 rpcbind-0.2.0-49.el7.x86_64
-rpm-4.11.3-46.el7_9.x86_64
-rpm-build-libs-4.11.3-46.el7_9.x86_64
-rpm-libs-4.11.3-46.el7_9.x86_64
-rpm-python-4.11.3-46.el7_9.x86_64
+rpm-4.11.3-48.el7_9.x86_64
+rpm-build-libs-4.11.3-48.el7_9.x86_64
+rpm-libs-4.11.3-48.el7_9.x86_64
+rpm-python-4.11.3-48.el7_9.x86_64
 rsync-3.1.2-10.el7.x86_64
 rsyslog-8.24.0-57.el7_9.1.x86_64
 ruby-2.0.0.648-36.el7.x86_64
@@ -476,6 +477,7 @@ shadow-utils-4.6-5.el7.x86_64
 shared-mime-info-1.8-5.el7.x86_64
 slang-2.2.4-11.el7.x86_64
 snappy-1.1.0-3.el7.x86_64
+spel-release-7-2.noarch
 sqlite-3.7.17-8.el7_7.1.x86_64
 stunnel-4.56-6.el7.x86_64
 sudo-1.8.23-10.el7_9.2.x86_64
```

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Review by eemperor — APPROVED** [review]
🚀

**Comment by lorengordon** [comment]
go codebuild go

**Pull request merged**
