### PR TITLE
Prepares version 2020.01.1

### PR DESCRIPTION
**Pull request by eemperor**
* New PR Alert to: @plus3it/spel

### CODE REVIEW

**Comment by lorengordon** [comment]
Need to add the vagrant manifest also...

**Comment by eemperor** [comment]
It's weird.  The vagrant manifest has no difference.  Not sure if there's some issue upstream but I didn't see anything obvious in the logs.  The redhat and centos manifests show minimal differences as well.

**Comment by lorengordon** [comment]
Ahh, that makes sense. We might have beat the RHEL/CentOS monthly patch update, or perhaps they're skipping January...

**Comment by ferricoxide** [comment]
> Ahh, that makes sense. We might have beat the RHEL/CentOS monthly patch update, or perhaps they're skipping January...

Looks like we may end up going 2+ months without a kernel-update:

~~~
$ yum --showduplicates list available kernel
[…ELIDED…]
Available Packages
kernel.x86_64                                              3.10.0-1062.el7                                                   base
kernel.x86_64                                              3.10.0-1062.1.1.el7                                               updates
kernel.x86_64                                              3.10.0-1062.1.2.el7                                               updates
kernel.x86_64                                              3.10.0-1062.4.1.el7                                               updates
kernel.x86_64                                              3.10.0-1062.4.2.el7                                               updates
kernel.x86_64                                              3.10.0-1062.4.3.el7                                               updates
kernel.x86_64                                              3.10.0-1062.7.1.el7                                               updates
kernel.x86_64                                              3.10.0-1062.9.1.el7                                               updates
[ferric@cataract ~]$ rpm -qi kernel-3.10.0-1062.9.1.el7.x86_64
Name        : kernel
Version     : 3.10.0
Release     : 1062.9.1.el7
Architecture: x86_64
Install Date: Fri 03 Jan 2020 02:38:03 PM UTC
Group       : System Environment/Kernel
Size        : 67088630
License     : GPLv2
Signature   : RSA/SHA256, Fri 06 Dec 2019 08:11:29 PM UTC, Key ID 24c6a8a7f4a80eb5
Source RPM  : kernel-3.10.0-1062.9.1.el7.src.rpm
Build Date  : Fri 06 Dec 2019 04:05:18 PM UTC
Build Host  : kbuilder.bsys.centos.org
Relocations : (not relocatable)
Packager    : CentOS BuildSystem <http://bugs.centos.org>
Vendor      : CentOS
URL         : http://www.kernel.org/
Summary     : The Linux kernel
Description :
The kernel package contains the Linux kernel (vmlinuz), the core of any
Linux operating system.  The kernel handles the basic functions
of the operating system: memory allocation, process allocation, device
input and output, etc.
~~~

Wonder if this means there was a security-flaw submitted just before the January kernel was getting ready to exit the release-pipeline forcing Red Hat (and, by  extension, CentOS.Org) to start afresh?

**Pull request merged**
