### PR TITLE
Improves logging/visibility by using a provisioner for pivot-root logic

### PR DESCRIPTION
**Pull request by lorengordon**
Shifts the pivot-root from userdata to a packer provisioner. This improves visibility into the build process since the provisioner output is logged.

We could move the `yum update` into the provisioner also. And perhaps the `setenforce 0`... But I think even without them, it is capturing all the commands where we've had problems in the past so they are logged and visible in the packer output...

* New PR Alert to: @plus3it/spel

### CODE REVIEW

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Review by oblandford-novetta — APPROVED** [review]
I don't see any issues

**Pull request merged**
