### PR TITLE
Updates readme with new hcl builders and inputs

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Comment by lorengordon** [comment]
go vagrant go

**Comment by lorengordon** [comment]
go vagrant go

**Comment by lorengordon** [comment]
go vagrant go

**Comment by lorengordon** [comment]
go vagrant go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go vagrant go

**Review by eemperor — APPROVED** [review]
🚢

**Pull request merged**
