### PR TITLE
Scope temporary security group to build systems IP address

### PR DESCRIPTION
**Pull request by confusdcodr**
Fixes # .

Changes offered/proposed in this pull request:
- Add temporary security group CIDR option to the packer template to define the CIDR of the build system dynamically.

* New PR Alert to: @plus3it/spel

### CODE REVIEW

**Comment by lorengordon** [comment]
@confusdcodr This looks great, can you also update the README to include the new variable?

**Comment by confusdcodr** [comment]
Yes, I can take a look at that.

**Comment by confusdcodr** [comment]
Documentation has been added.

**Comment by lorengordon** [comment]
Go codebuild go

**Pull request merged**
