### PR TITLE
Ensures MKFSFORCEOPT is set when executing amigen scripts

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
@plus3it/spel The codebuild jobs are getting past the failure point, this ought to be ready for review...

**Comment by eemperor** [comment]
@lorengordon Is this just a temp fix until this https://github.com/plus3it/AMIgen7/pull/71/files is re-worked?

**Comment by lorengordon** [comment]
Could be? If the amigen approach changes, we'll likely need to adjust here accordingly.

**Comment by ferricoxide** [comment]
> 
> 
> @lorengordon Is this just a temp fix until this https://github.com/plus3it/AMIgen7/pull/71/files is re-worked?

??

**Comment by eemperor** [comment]
> > @lorengordon Is this just a temp fix until this https://github.com/plus3it/AMIgen7/pull/71/files is re-worked?
> 
> ??

Think I was referring to where `MKFSFORCEOPT` gets set in `DiskSetup.sh`.  Looking at this again, maybe we need to add the `-f` option when calling `DiskSetup.sh`?

**Comment by ferricoxide** [comment]
> Think I was referring to where `MKFSFORCEOPT` gets set in `DiskSetup.sh`. Looking at this again, maybe we need to add the `-f` option when calling `DiskSetup.sh`?

I _thought_ I'd updated the `DiskSetup.sh` to _select_ the requisite force option based on the "selected" fstype.

**Comment by ferricoxide** [comment]
Yeah... The case statement sets it ...[when activated via the `-f` flag/argument](https://github.com/ferricoxide/AMIgen7/blob/41fab2c63b6ff4e127421d0e1de2a5a3519abcfc/DiskSetup.sh#L175-L189), but looks like I forgot to set it when someone relies on ["ext4 as default"](https://github.com/ferricoxide/AMIgen7/blob/41fab2c63b6ff4e127421d0e1de2a5a3519abcfc/DiskSetup.sh#L9) (I don't have a `MKFSFORCEOPT=` outside of the switch-block).

Bugger. :anger:

**Comment by lorengordon** [comment]
The fundamental issue here is that spel use's bash unofficial strict mode when executing scripts, `set -eu -o pipefail`. `DiskSetup.sh` uses functions that depend on environment variables where the value is set _after_ the function is defined. That means the variable is undefined when bash loads the function, which triggers the `set -u` failure. The value _is_ set by the time the function is actually invoked, so this is really just an oddity of how bash loads the function and an interaction with `set -u`.

By exporting a value for the environment variable in spel, we circumvent the `set -u` trigger.

Handling it in amigen7 by setting a throwaway value at the top of `DiskSetup.sh` didn't make much sense, since the opts handling would override it anyway, and I didn't want to try to rework the entire opts handling or how arguments are passed to the functions (by removing globals or somesuch).

**Comment by ferricoxide** [comment]
> Handling it in amigen7 by setting a throwaway value at the top of `DiskSetup.sh` didn't make much sense, since the opts handling would override it anyway, and I didn't want to try to rework the entire opts handling or how arguments are passed to the functions (by removing globals or somesuch).

It's not a "throwaway", per se: it's a defaulted value. The intention of having it is so that dependant projects don't need to add `-f ext4` just to get the previous (no flag/arg) behavior back. Unfortunately, I failed to also set the new `MKFSFORCEOPT=` var/val. Had I fully accounted for the "legacy" ("no flag/arg") mode, there'd have been no changes required for spel to continue its prior functioning (only change that _should_ have been required for spel would have been to add XFS-enabled AMI generation content).

**Pull request merged**
