### PR TITLE
Adds DoD/WCF certs to spel images

### PR DESCRIPTION
**Pull request by eemperor**
Fixes # .

Changes offered/proposed in this pull request:
- 
- 
- 

* New PR Alert to: @plus3it/spel

### CODE REVIEW

**Comment by eemperor** [comment]
go codebuild go

**Review by lorengordon — APPROVED** [review]
Approved pending the Codebuild jobs...

**Comment by eemperor** [comment]
go codebuild go

**Comment by eemperor** [comment]
go codebuid go

**Comment by eemperor** [comment]
go codebuild go

**Comment by eemperor** [comment]
@lorengordon Can you re-approve please?

**Review by lorengordon — APPROVED** [review]

**Pull request merged**
