### PR TITLE
Updates AMIs to use EBS GP3 volumes

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by eemperor** [comment]
I didn't see this in the PR:

https://github.com/plus3it/spel/blob/master/build/build.sh#L21

**Comment by lorengordon** [comment]
> I didn't see this in the PR:
> 
> [`master`/build/build.sh#L21](https://github.com/plus3it/spel/blob/master/build/build.sh?rgh-link-date=2023-11-28T19%3A15%3A53Z#L21)

Ooops. I had changed the file locally, but hadn't saved it. So find-in-files for "gp2" didn't turn it up, and git status didn't see any changed files! Pushed...

**Review by eemperor — APPROVED** [review]

**Pull request merged**
