### PR TITLE
Uses new amazon-ebssurrogate volume swap feature to skip pivot-root

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go vagrant go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go vagrant go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go vagrant go

**Review by ferricoxide — APPROVED** [review]
Not seeing anything that sticks out as odd/wrong. :)

**Pull request merged**
