### PR TITLE
Removes .box and .ova files so they are not archived as artifacts

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Comment by lorengordon** [comment]
go vagrant go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go vagrant go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go vagrant go

**Comment by lorengordon** [comment]
go codebuild go

**Review by eemperor — APPROVED** [review]
🚀

**Pull request merged**
